import openai
openai.api_key = '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'
def chat(user_input):
    #This section of code works to take the user input and send it to the openai api and returns the response generated by the OpenAI model"""

    response = openai.Completion.create(
        engine="gpt-3.5-turbo-instruct", #model for text generation and completion
        prompt=f"**User:**{user_input}\n**Chatbot:** ",
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.7,#parameter that controls the randomness of the text generated; higher value = more temperature
        #0.7-0.9 are the mid-ground values...
        )
    return response.choices[0].text.strip()

while True:
    user_input = input("User: ")
    if user_input.lower() =="quit":
        break
    chatbot_response = chat(user_input)
    print(f"Chatbot: {chatbot_response}")